[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
description = "solarti-token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "solarti-token-2022-test"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []
proof-program = ["solarti-token-2022/proof-program"]

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
borsh = "0.10"
futures-util = "0.3"
miraland-program = "1.14.18"
miraland-program-test = "1.18.2"
miraland-sdk = "1.14.18"
solarti-associated-token-account = { version = "2.0", path = "../../associated-token-account/program" }
solarti-memo = { version = "4.0.0", path = "../../memo/program", features = ["no-entrypoint"] }
solarti-pod = { version = "0.1.0", path = "../../libraries/pod" }
solarti-token-2022 = { version = "0.9", path="../program-2022", features = ["no-entrypoint"] }
solarti-instruction-padding = { version = "0.1.0", path="../../instruction-padding/program", features = ["no-entrypoint"] }
solarti-token-client = { version = "0.4", path = "../client" }
solarti-token-group-interface = { version = "0.1", path = "../../token-group/interface" }
solarti-token-metadata-interface = { version = "0.2", path = "../../token-metadata/interface" }
solarti-transfer-hook-example = { version = "0.3", path="../transfer-hook/example", features = ["no-entrypoint"] }
solarti-transfer-hook-interface = { version = "0.3", path="../transfer-hook/interface" }
test-case = "3.2"
