[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "solarti-token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "solarti-token-2022-test"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []
proof-program = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
miraland-program = {path = "../../../miraland-1.14.17/sdk/program", version = "1.14.17-rc4"}
miraland-program-test = {path = "../../../miraland-1.14.17/program-test", version = "1.14.17-rc4"}
miraland-sdk = {path = "../../../miraland-1.14.17/sdk", version = "1.14.17-rc4"}
solarti-associated-token-account = { version = "1.1", path = "../../associated-token-account/program" }
solarti-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
solarti-token-2022 = { version = "0.6", path="../program-2022", features = ["no-entrypoint"] }
solarti-instruction-padding = { version = "0.1.0", path="../../instruction-padding/program", features = ["no-entrypoint"] }
solarti-token-client = { version = "0.4", path = "../client" }
