[package]
name = "solarti-token-swap-fuzz"
version = "0.0.1"
description = "Solana Program Library Token Swap Fuzzer"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
honggfuzz = { version = "0.5.55" }
arbitrary = { version = "1.0", features = ["derive"] }
solana-program = "1.14.12"
solarti-math = { version = "0.1", path = "../../../libraries/math", features = [ "no-entrypoint" ] }
solarti-token = { version = "3.5", path = "../../../token/program", features = [ "no-entrypoint" ] }
solarti-token-swap = { path = "..", features = ["fuzz", "no-entrypoint"] }

[[bin]]
name = "token-swap-instructions"
path = "src/instructions.rs"
test = false
doc = false
