[package]
name = "solarti-token-swap-fuzz"
version = "0.0.1"
description = "Solarti Program Library Token Swap Fuzzer"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
honggfuzz = { version = "0.5.55" }
arbitrary = { version = "=1.0.3", features = ["derive"] }
derive_arbitrary = "=1.0.2"
miraland-program = "1.14.17"
solarti-math = { version = "0.1", path = "../../../libraries/math", features = [ "no-entrypoint" ] }
solarti-token = { version = "3.5", path = "../../../token/program", features = [ "no-entrypoint" ] }
solarti-token-swap = { path = "..", features = ["fuzz", "no-entrypoint"] }

[[bin]]
name = "token-swap-instructions"
path = "src/instructions.rs"
test = false
doc = false

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_swap_fuzz"