[package]
name = "test-client"
version = "0.1.1"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
publish = false
edition = "2021"

# Used to ensure that SPL programs are buildable by external clients

[dependencies]
miraland-sdk = ">=1.18.2"
solarti-memo = { path = "../../memo/program", features = [ "no-entrypoint" ] }
solarti-token = { path = "../../token/program", features = [ "no-entrypoint" ] }
solarti-token-swap = { path = "../../token-swap/program", features = [ "no-entrypoint" ] }
