[package]
name = "solarti-discriminator-syn"
version = "0.1.4"
description = "Token parsing and generating library for the `solarti-discriminator` library"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
sha2 = "0.10"
syn = { version = "2.0", features = ["full"] }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_discriminator_syn"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
