[package]
name = "solarti-token-lending"
version = "0.2.1"
description = "Solarti Program Library Token Lending"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.7"
bytemuck = "1.14.0"
num-derive = "0.4"
num-traits = "0.2"
miraland-program = ">=1.18.2"
solarti-token = { version = "4.0", path = "../../token/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
uint = "0.9"

[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.4"
miraland-program-test = ">=1.18.2"
miraland-sdk = ">=1.18.2"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_lending"