[package]
name = "solarti-governance-addin-mock"
version = "0.1.4"
description = "Solarti Program Library Governance Voter Weight Addin Program"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.2"
borsh = "0.10.3"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.127"
serde_derive = "1.0.103"
miraland-program = "1.14.18"
solarti-token = { version = "3.5", path = "../../../token/program", features = [ "no-entrypoint" ] }
solarti-governance-addin-api= { version = "0.1", path ="../../addin-api"}
solarti-governance-tools= { version = "0.1", path ="../../tools"}
thiserror = "1.0"


[dev-dependencies]
assert_matches = "1.5.0"
base64 = "0.13"
proptest = "1.0"
miraland-program-test = "1.14.18"
miraland-sdk = "1.14.18"
solarti-governance-test-sdk = { version = "0.1", path ="../../test-sdk"}


[lib]
crate-type = ["cdylib", "lib"]
name = "spl_governance_addin_mock"