anchor_version = "0.14.0"

[workspace]
members = ["program"]

[provider]
cluster = "devnet"
wallet = "~/.config/miraland/id.json"

[programs.devnet]
solarti-token-lending = "Lendom2HkAKTe8bLUMxDxpBd8kCYUbZjECGtx9RFV7c"
