anchor_version = "0.26.1"
miraland_version = ">=1.18.2"

[workspace]
members = [
  "governance/program",
  "governance/chat/program",
  "memo/program",
  "stake-pool/program",
  "token/program",
  "token/program-2022",
]
exclude = [
  "account-compression/"
]

[provider]
cluster = "mainnet"
wallet = "~/.config/miraland/id.json"

[programs.mainnet]
spl_governance = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
spl_governance_chat = "gCHAtYKrUUktTVzE4hEnZdLV4LXrdBf6Hh9qMaJALET"
spl_stake_pool = "spooqgqqDxZgVc3pR6EvuVFZJ1kj7ABM4Hccz1gwAN1"
spl_token = "Token4Q2B47VCdUy8u3rSTMMk2bGA1k7eN8qfKSzdiM"
spl_token_2022 = "Token8N5ecJeFxL83iFa2h7AgJ8AtufM7bbg63LrW89"
