[workspace]
resolver = "2"

members = [
  "associated-token-account/program",
  "associated-token-account/program-test",
  # "binary-option/program",
  # "binary-oracle-pair/program",
  # "examples/rust/cross-program-invocation",
  # "examples/rust/custom-heap",
  # "examples/rust/logging",
  # "examples/rust/sysvar",
  # "examples/rust/transfer-lamports",
  # "examples/rust/transfer-tokens",
  "feature-proposal/program",
  "feature-proposal/cli",
  # "governance/addin-mock/program",
  # "governance/addin-api",
  # "governance/program",
  # "governance/test-sdk",
  # "governance/tools",
  # "governance/chat/program",
  "instruction-padding/program",
  "libraries/math",
  "libraries/concurrent-merkle-tree",
  "libraries/discriminator",
  "libraries/math",
  "libraries/merkle-tree-reference",
  "libraries/pod",
  "libraries/program-error",
  "libraries/tlv-account-resolution",
  "libraries/type-length-value",
  # "libraries/type-length-value-derive-test",
  "memo/program",
  # "name-service/program",
  # "managed-token/program",
  # "record/program",
  # "shared-memory/program",
  # "stake-pool/cli",
  # "stake-pool/program",
  # "stateless-asks/program",
  # "token-collection/program",
  # "token-group/example",
  "token-group/interface",
  # "token-lending/cli",
  # "token-lending/program",
  # "token-metadata/example",
  "token-metadata/interface",
  # "token-swap/program",
  # "token-swap/program/fuzz",
  # "token-upgrade/cli",
  # "token-upgrade/program",
  "token/cli",
  "token/program",
  "token/program-2022",
  # "token/program-2022-test",
  # "token/transfer-hook/cli",
  # "token/transfer-hook/example",
  "token/transfer-hook/interface",
  "token/client",
  # "utils/cgen",
  # "utils/test-client",
  # "token-lending/flash_loan_receiver",
]
exclude = [
  "farms/farm-client",
  "farms/farm-ctrl",
  "farms/farm-rpc",
  "farms/farm-sdk",
  "farms/fund",
  "farms/router-main",
  "farms/router-raydium",
  "farms/router-saber",
  "farms/router-orca",
  "farms/vaults",
]

[profile.dev]
split-debuginfo = "unpacked"
