#!/usr/bin/env bash
#
# Patches the SPL crates for developing against a local miraland monorepo
#

miraland_dir=$1
if [[ -z $miraland_dir ]]; then
  echo "Usage: $0 <path-to-miraland-monorepo>"
  exit 1
fi

workspace_crates=(
  Cargo.toml
)

if [[ ! -r "$miraland_dir"/scripts/read-cargo-variable.sh ]]; then
  echo "$miraland_dir is not a path to the miraland monorepo"
  exit 1
fi

set -e

miraland_dir=$(cd "$miraland_dir" && pwd)
cd "$(dirname "$0")"
project_root=$(pwd)

source "$miraland_dir"/scripts/read-cargo-variable.sh

# The toolchain file only exists in version >= 1.15
toolchain_file="$miraland_dir"/rust-toolchain.toml
if [[ -f "$toolchain_file" ]]; then
  cp "$toolchain_file" .
fi

# only add exclude rule when miraland root is under spl root
if echo "$miraland_dir" | grep "^$project_root" > /dev/null; then
  echo "Excluding $miraland_dir from workspace"
  echo
  for crate in "${workspace_crates[@]}"; do
    if grep -q "exclude.*$miraland_dir" "$crate"; then
      echo "$crate is already patched"
    else
      sed -i'' "$crate" -e "/exclude/a \ \ \"$miraland_dir\","
    fi
  done
fi

# get version from Cargo.toml first. if it is empty, get it from other places.
miraland_ver="$(readCargoVariable version "$miraland_dir"/Cargo.toml)"
miraland_ver=${miraland_ver:-$(readCargoVariable version "$miraland_dir"/sdk/Cargo.toml)}

crates_map=()
crates_map+=("miraland-account-decoder account-decoder")
crates_map+=("miraland-banks-client banks-client")
crates_map+=("miraland-banks-interface banks-interface")
crates_map+=("miraland-banks-server banks-server")
crates_map+=("miraland-bloom bloom")
crates_map+=("miraland-bucket-map bucket_map")
crates_map+=("miraland-clap-utils clap-utils")
crates_map+=("miraland-clap-v3-utils clap-v3-utils")
crates_map+=("miraland-cli-config cli-config")
crates_map+=("miraland-cli-output cli-output")
crates_map+=("miraland-client client")
crates_map+=("miraland-connection-cache connection-cache")
crates_map+=("miraland-core core")
crates_map+=("miraland-entry entry")
crates_map+=("miraland-faucet faucet")
crates_map+=("miraland-frozen-abi frozen-abi")
crates_map+=("miraland-frozen-abi-macro frozen-abi/macro")
crates_map+=("miraland-geyser-plugin-interface geyser-plugin-interface")
crates_map+=("miraland-geyser-plugin-manager geyser-plugin-manager")
crates_map+=("miraland-gossip gossip")
crates_map+=("miraland-ledger ledger")
crates_map+=("miraland-logger logger")
crates_map+=("miraland-measure measure")
crates_map+=("miraland-merkle-tree merkle-tree")
crates_map+=("miraland-metrics metrics")
crates_map+=("miraland-net-utils net-utils")
crates_map+=("miraland-perf perf")
crates_map+=("miraland-poh poh")
crates_map+=("miraland-program-runtime program-runtime")
crates_map+=("miraland-program-test program-test")
crates_map+=("miraland-address-lookup-table-program programs/address-lookup-table")
crates_map+=("miraland-bpf-loader-program programs/bpf_loader")
crates_map+=("miraland-compute-budget-program programs/compute-budget")
crates_map+=("miraland-config-program programs/config")
crates_map+=("miraland-stake-program programs/stake")
crates_map+=("miraland-vote-program programs/vote")
crates_map+=("miraland-zk-token-proof-program programs/zk-token-proof")
crates_map+=("miraland-pubsub-client pubsub-client")
crates_map+=("miraland-quic-client quic-client")
crates_map+=("miraland-rayon-threadlimit rayon-threadlimit")
crates_map+=("miraland-remote-wallet remote-wallet")
crates_map+=("miraland-rpc rpc")
crates_map+=("miraland-rpc-client rpc-client")
crates_map+=("miraland-rpc-client-api rpc-client-api")
crates_map+=("miraland-rpc-client-nonce-utils rpc-client-nonce-utils")
crates_map+=("miraland-runtime runtime")
crates_map+=("miraland-sdk sdk")
crates_map+=("miraland-sdk-macro sdk/macro")
crates_map+=("miraland-program sdk/program")
crates_map+=("miraland-send-transaction-service send-transaction-service")
crates_map+=("miraland-storage-bigtable storage-bigtable")
crates_map+=("miraland-storage-proto storage-proto")
crates_map+=("miraland-streamer streamer")
crates_map+=("miraland-test-validator test-validator")
crates_map+=("miraland-thin-client thin-client")
crates_map+=("miraland-tpu-client tpu-client")
crates_map+=("miraland-transaction-status transaction-status")
crates_map+=("miraland-udp-client udp-client")
crates_map+=("miraland-version version")
crates_map+=("miraland-zk-token-sdk zk-token-sdk")

patch_crates=()
for map_entry in "${crates_map[@]}"; do
  read -r crate_name crate_path <<<"$map_entry"
  full_path="$miraland_dir/$crate_path"
  if [[ -r "$full_path/Cargo.toml" ]]; then
    patch_crates+=("$crate_name = { path = \"$full_path\" }")
  fi
done

echo "Patching in $miraland_ver from $miraland_dir"
echo
for crate in "${workspace_crates[@]}"; do
  if grep -q "# The following entries are auto-generated by $0" "$crate"; then
    echo "$crate is already patched"
  else
    if ! grep -q '\[patch.crates-io\]' "$crate"; then
      echo "[patch.crates-io]" >> "$crate"
    fi
    cat >> "$crate" <<PATCH
# The following entries are auto-generated by $0
$(printf "%s\n" "${patch_crates[@]}")
PATCH
  fi
done

./update-miraland-dependencies.sh "$miraland_ver"
