packages:
  - "account-compression/sdk"
  - "libraries/type-length-value/js"
  - "memo/js"
  - "name-service/js"
  - "single-pool/js/packages/*"
  - "stake-pool/js"
  - "token/js"
  - "token-lending/js"
  - "token-metadata/js"
  - "token-swap/js"
