[package]
name = "solarti-token-metadata-example"
version = "0.2.3"
description = "Solarti Program Library Token Metadata Example Program"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
miraland-program = ">=1.18.5, <1.19.0"
solarti-token-2022 = { version = "1.0.0", path = "../../token/program-2022", features = [
  "no-entrypoint",
] }
solarti-token-metadata-interface = { version = "0.2.0", path = "../interface" }
solarti-type-length-value = { version = "0.3.0", path = "../../libraries/type-length-value" }
solarti-pod = { version = "0.1.0", path = "../../libraries/pod" }

[dev-dependencies]
miraland-program-test = ">=1.18.5, <1.19.0"
miraland-sdk = ">=1.18.5, <1.19.0"
solarti-token-client = { version = "0.5", path = "../../token/client" }
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_metadata_example"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
