[package]
name = "cgen"
version = "0.1.0"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
publish = false
edition = "2021"

[dependencies]
cbindgen = "=0.16.0"
