[package]
name = "solarti-token-swap"
version = "3.0.0"
description = "Solarti Program Library Token Swap"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
production = []
fuzz = ["arbitrary", "roots"]

[dependencies]
arrayref = "0.3.6"
enum_dispatch = "0.3.7"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.14.12"
solarti-math = { version = "0.1", path = "../../libraries/math", features = [ "no-entrypoint" ] }
solarti-token = { version = "3.5", path = "../../token/program", features = [ "no-entrypoint" ] }
solarti-token-2022 = { version = "0.6", path = "../../token/program-2022", features = [ "no-entrypoint" ] }
thiserror = "1.0"
arbitrary = { version = "1.0", features = ["derive"], optional = true }
roots = { version = "0.0.7", optional = true }

[dev-dependencies]
proptest = "1.0"
roots = "0.0.7"
solana-sdk = "1.14.12"
test-case = "2.2"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_swap"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
