[package]
name = "solarti-governance-chat"
version = "0.2.8"
description = "Solarti Program Library Governance Chat Program"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.7"
bincode = "1.3.2"
borsh = "1.3.0"
num-derive = "0.4"
num-traits = "0.2"
serde = "1.0.193"
serde_derive = "1.0.103"
miraland-program = ">=1.18.2"
solarti-token = { version = "4.0", path = "../../../token/program", features = [ "no-entrypoint" ] }
solarti-governance= { version = "3.1", path ="../../program", features = [ "no-entrypoint" ]}
solarti-governance-tools= { version = "0.1", path ="../../tools"}
solarti-governance-addin-api= { version = "0.1", path ="../../addin-api"}
thiserror = "1.0"


[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.4"
miraland-program-test = ">=1.18.2"
miraland-sdk = ">=1.18.2"
solarti-governance-test-sdk = { version = "0.1", path ="../../test-sdk"}
solarti-governance-addin-mock = { version = "0.1", path ="../../addin-mock/program"}


[lib]
crate-type = ["cdylib", "lib"]
name = "spl_governance_chat"