[package]
name = "solarti-token-group-example"
version = "0.1.0"
description = "Solarti Program Library Token Group Example"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
miraland-program = ">1.19.0"
solarti-pod = { version = "0.1.0", path = "../../libraries/pod" }
solarti-token-2022 = { version = "1.1.0", path = "../../token/program-2022", features = [
  "no-entrypoint",
] }
solarti-token-group-interface = { version = "0.1.0", path = "../interface" }
solarti-type-length-value = { version = "0.3.0", path = "../../libraries/type-length-value" }

[dev-dependencies]
miraland-program-test = ">1.19.0"
miraland-sdk = ">1.19.0"
solarti-discriminator = { version = "0.1.10", path = "../../libraries/discriminator" }
solarti-token-client = { version = "0.6.0", path = "../../token/client" }
solarti-token-metadata-interface = { version = "0.2", path = "../../token-metadata/interface" }

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_group_example"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
