[package]
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
description = "SOLARTI Token Lending CLI"
edition = "2021"
homepage = "https://spl.miraland.io/token-lending"
license = "Apache-2.0"
name = "solarti-token-lending-cli"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "0.2.1"

[dependencies]
clap = "2.33.3"
miraland-clap-utils = ">1.19.0"
miraland-cli-config = ">1.19.0"
miraland-client = ">1.19.0"
miraland-logger = ">1.19.0"
miraland-sdk = ">1.19.0"
miraland-program = ">1.19.0"
solarti-token-lending = { version = "0.2", path = "../program", features = [
  "no-entrypoint",
] }
solarti-token = { version = "4.0", path = "../../token/program", features = [
  "no-entrypoint",
] }

[[bin]]
name = "solarti-token-lending"
path = "src/main.rs"
