[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
description = "SOLARTI Token Lending CLI"
edition = "2021"
homepage = "https://spl.solana.com/token-lending"
license = "Apache-2.0"
name = "solarti-token-lending-cli"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "0.2.0"

[dependencies]
clap = "2.33.3"
miraland-clap-utils = "=1.14.17"
miraland-cli-config = "=1.14.17"
miraland-client = "=1.14.17"
miraland-logger = "=1.14.17"
miraland-sdk = "=1.14.17"
miraland-program = "=1.14.17"
solarti-token-lending = { version = "0.2", path="../program", features = [ "no-entrypoint" ] }
solarti-token = { version = "3.5", path="../../token/program", features = [ "no-entrypoint" ]  }

[[bin]]
name = "solarti-token-lending"
path = "src/main.rs"
