[package]
name = "solarti-example-cross-program-invocation"
version = "1.0.0"
description = "Solarti Program Library Cross Program Invocation Example"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
miraland-program = ">1.19.0"

[dev-dependencies]
miraland-program-test = ">1.19.0"
miraland-sdk = ">1.19.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_example_cross_program_invocation"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
