[package]
name = "solarti-noop"
version = "0.2.1"
description = "Solarti Program Library No-op Program"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_noop"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
miraland-program = ">1.19.0"
