[package]
name = "solarti-noop"
version = "0.1.3"
description = "Solarti Program Library No-op Program"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_noop"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-program = "1.13.5"
