[package]
name = "solarti-discriminator-derive"
version = "0.1.10"
description = "Derive macro library for the `solarti-discriminator` library"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
quote = "1.0"
solarti-discriminator-syn = { version = "0.1.10", path = "../syn" }
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true
name = "spl_discriminator_derive"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
