[package]
name = "solarti-memo"
version = "3.0.2"
description = "Solarti Program Library Memo"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
miraland-program = {path = "../../../miraland-1.14.17/sdk/program", version = "1.14.17-rc3"}

[dev-dependencies]
miraland-program-test = {path = "../../../miraland-1.14.17/program-test", version = "1.14.17-rc3"}
miraland-sdk = {path = "../../../miraland-1.14.17/sdk", version = "1.14.17-rc3"}

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_memo"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
