[package]
name = "solarti-token"
version = "3.5.0"
description = "Solarti Program Library Token"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.6"
bytemuck = "1.13.0"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.9"
solana-program = "1.14.12"
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.0"
serial_test = "0.5.1"
solana-program-test = "1.14.12"
solana-sdk = "1.14.12"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
