[package]
name = "solarti-token"
version = "4.1.1"
description = "Solarti Program Library Token"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.7"
bytemuck = "1.15.0"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.1"
miraland-program = ">=1.18.2"
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.4"
serial_test = "2.0.0"
miraland-program-test = ">=1.18.2"
miraland-sdk = ">=1.18.2"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
