[package]
name = "solarti-token"
version = "3.5.4"
description = "Solarti Program Library Token"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.6"
bytemuck = "1.13.0"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.9"
miraland-program = "=1.14.17-rc6"
thiserror = "1.0"
winnow = "=0.4.1"

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.0"
serial_test = "0.5.1"
miraland-program-test = "=1.14.17-rc6"
miraland-sdk = "=1.14.17-rc6"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
