[package]
name = "solarti-account-compression"
version = "0.1.9"
description = "Solarti Program Library Account Compression Program"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_account_compression"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.1"
bytemuck = "1.19.0"
solarti-concurrent-merkle-tree = { version = "0.2", path = "../../../libraries/concurrent-merkle-tree", features = [
  "mln-log",
] }
solarti-noop = { version = "0.2.0", path = "../noop", features = [
  "no-entrypoint",
] }

[profile.release]
overflow-checks = true
