[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
description = "Solarti Token Command-line Utility"
edition = "2021"
homepage = "https://spl.miraland.top/token"
license = "Apache-2.0"
name = "solarti-token-cli"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "3.1.0"

[build-dependencies]
walkdir = "2"

[dependencies]
base64 = "0.21.5"
clap = "2.33.3"
console = "0.15.7"
futures = "0.3"
serde = "1.0.197"
serde_derive = "1.0.103"
serde_json = "1.0.108"
miraland-account-decoder = "1.18.2"
miraland-clap-utils = "1.18.2"
miraland-cli-config = "1.18.2"
miraland-cli-output = "1.18.2"
miraland-client = "1.18.2"
miraland-logger = "1.18.2"
miraland-remote-wallet = "1.18.2"
miraland-sdk = "1.18.2"
miraland-transaction-status = "1.18.2"
solarti-token = { version = "4.0", path = "../program", features = [
  "no-entrypoint",
] }
solarti-token-2022 = { version = "1.0", path = "../program-2022", features = [
  "no-entrypoint",
] }
solarti-token-client = { version = "0.5.0", path = "../client" }
solarti-token-metadata-interface = { version = "0.2.3", path = "../../token-metadata/interface" }
solarti-associated-token-account = { version = "2.1.0", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
solarti-memo = { version = "4.0.0", path = "../../memo/program", features = [
  "no-entrypoint",
] }
strum = "0.25"
strum_macros = "0.25"
tokio = "1.35"

[dev-dependencies]
miraland-test-validator = "1.18.2"
assert_cmd = "2.0.12"
libtest-mimic = "0.6"
serial_test = "2.0.0"
tempfile = "3.8.1"

[[bin]]
name = "solarti-token"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_cli"

[[test]]
name = "command"
path = "tests/command.rs"
harness = false
