[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
description = "Solarti Token Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "solarti-token-cli"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "2.3.0"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33.3"
console = "0.15.0"
indicatif = "0.16.2"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.68"
miraland-account-decoder = "=1.14.17-rc4"
miraland-clap-utils = "=1.14.17-rc4"
miraland-cli-config = "=1.14.17-rc4"
miraland-cli-output = "=1.14.17-rc4"
miraland-client = "=1.14.17-rc4"
miraland-logger = "=1.14.17-rc4"
miraland-remote-wallet = "=1.14.17-rc4"
miraland-sdk = "=1.14.17-rc4"
miraland-transaction-status = "=1.14.17-rc4"
solarti-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
solarti-token-2022 = { version = "0.6", path="../program-2022", features = [ "no-entrypoint" ] }
solarti-token-client = { version = "0.4", path="../client" }
solarti-associated-token-account = { version = "1.1", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
solarti-memo = { version = "3.0", path="../../memo/program", features = ["no-entrypoint"] }
strum = "0.24"
strum_macros = "0.24"
tokio = "1.14"

[dev-dependencies]
miraland-test-validator = "=1.14.17-rc4"
assert_cmd = "=2.0.4"
predicates-tree = "=1.0.5"
predicates-core = "=1.0.3"
serial_test = "0.8.0"
tempfile = "3.4.0"

[[bin]]
name = "solarti-token"
path = "src/main.rs"
