[package]
name = "solarti-shared-memory"
version = "2.0.6"
description = "Solarti Program Library Shared-memory"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
arrayref = "0.3.6"
solana-program = "=1.14.12"

[dev-dependencies]
solana-program-test = "=1.14.12"
solana-sdk = "=1.14.12"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_shared_memory"