[package]
name = "solarti-token-wrap"
version = "0.1.0"
description = "Solarti Program Library Token Wrap"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
num_enum = "0.7"
miraland-program = ">1.19.0"
solarti-associated-token-account = { version = "2.2.0", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
solarti-token = { version = "4.2.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
solarti-token-2022 = { version = "1.1.0", path = "../../token/program-2022", features = [
  "no-entrypoint",
] }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_wrap"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
