[package]
name = "solarti-feature-proposal-cli"
version = "1.2.0"
description = "SOLARTI Feature Proposal Command-line Utility"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
clap = "2.33.3"
solana-clap-utils = "1.14.12"
solana-cli-config = "1.14.12"
solana-client = "1.14.12"
solana-logger = "1.14.12"
solana-sdk = "1.14.12"
spl-feature-proposal = { version = "1.0", path = "../program", features = ["no-entrypoint"] }

[[bin]]
name = "solarti-feature-proposal"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
