[package]
name = "spl-token-2022"
version = "0.9.0"
description = "Solana Program Library Token 2022"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []
serde-traits = ["dep:serde", "dep:serde_with", "dep:base64", "spl-pod/serde-traits"]
# Remove these features once the underlying syscalls are released on all networks
default = ["zk-ops"]
zk-ops = []
proof-program = []

[dependencies]
arrayref = "0.3.7"
bytemuck = { version = "1.14.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.1"
solana-program = "1.17.2"
solana-zk-token-sdk = "1.17.2"
spl-memo = { version = "4.0.0", path = "../../memo/program", features = [ "no-entrypoint" ] }
spl-token = { version = "4.0",  path = "../program", features = ["no-entrypoint"] }
spl-token-group-interface = { version = "0.1.0", path = "../../token-group/interface" }
spl-token-metadata-interface = { version = "0.2.0", path = "../../token-metadata/interface" }
spl-transfer-hook-interface = { version = "0.3.0", path = "../transfer-hook/interface" }
spl-type-length-value = { version = "0.3.0", path = "../../libraries/type-length-value" }
spl-pod = { version = "0.1.0", path = "../../libraries/pod" }
thiserror = "1.0"
serde = { version = "1.0.192", optional = true }
serde_with = { version = "3.4.0", optional = true }
base64 = { version = "0.21.5", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.4"
serial_test = "2.0.0"
solana-program-test = "1.17.2"
solana-sdk = "1.17.2"
serde_json = "1.0.108"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
