[package]
name = "solarti-token-2022"
version = "0.6.2"
description = "Solarti Program Library Token 2022"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []
serde-traits = ["serde", "serde_with"]
# Remove these features once the underlying syscalls are released on all networks
default = ["zk-ops"]
zk-ops = []
proof-program = []

[dependencies]
arrayref = "0.3.6"
bytemuck = { version = "1.13.0", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.9"
miraland-program = "=1.14.17-rc3"
miraland-zk-token-sdk = {path = "../../../miraland-1.14.17/zk-token-sdk", version = "1.14.17-rc4"}
solarti-memo = { version = "3.0.1", path = "../../memo/program", features = [ "no-entrypoint" ] }
solarti-token = { version = "3.5",  path = "../program", features = ["no-entrypoint"] }
thiserror = "1.0"
serde = { version = "1.0.136", optional = true }
serde_with = { version = "1.14.0", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.0"
serial_test = "0.5.1"
solana-program-test = "=1.14.17"
miraland-sdk = "=1.14.17-rc3"
serde_json = "1.0.81"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_2022"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
