[package]
name = "solarti-token-2022"
version = "1.0.2"
description = "Solarti Program Library Token 2022"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []
serde-traits = [
  "dep:serde",
  "dep:serde_with",
  "dep:base64",
  "solarti-pod/serde-traits",
]
default = ["token-group", "zk-ops"]
# Remove this feature once the underlying syscalls are released on all networks
zk-ops = []
# Remove this feature once the token group implementation has been audited
token-group = []

[dependencies]
arrayref = "0.3.7"
bytemuck = { version = "1.14.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.1"
miraland-program = ">=1.18.2, <1.19.0"
miraland-security-txt = "1.1.1"
miraland-zk-token-sdk = ">=1.18.2, <1.19.0"
solarti-memo = { version = "4.0.3", path = "../../memo/program", features = [
  "no-entrypoint",
] }
solarti-token = { version = "4.1.2", path = "../program", features = [
  "no-entrypoint",
] }
solarti-token-group-interface = { version = "0.1.3", path = "../../token-group/interface" }
solarti-token-metadata-interface = { version = "0.2.5", path = "../../token-metadata/interface" }
solarti-transfer-hook-interface = { version = "0.4.2", path = "../transfer-hook/interface" }
solarti-type-length-value = { version = "0.3.6", path = "../../libraries/type-length-value" }
solarti-pod = { version = "0.1.7", path = "../../libraries/pod" }
thiserror = "1.0"
serde = { version = "1.0.193", optional = true }
serde_with = { version = "3.4.0", optional = true }
base64 = { version = "0.21.5", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.4"
serial_test = "2.0.0"
miraland-program-test = ">=1.18.2, <1.19.0"
miraland-sdk = ">=1.18.2, <1.19.0"
serde_json = "1.0.108"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_2022"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
