[package]
name = "solarti-token-upgrade-cli"
version = "0.1.3"
description = "SOLARTI Token Upgrade Command-line Utility"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = { version = "3", features = ["cargo"] }
futures-util = "0.3.28"
miraland-clap-v3-utils = "1.14.18"
miraland-cli-config = "1.14.18"
miraland-client = "1.14.18"
miraland-logger = "1.14.18"
miraland-remote-wallet = "1.14.18"
miraland-sdk = "1.18.2"
solarti-associated-token-account = { version = "2.0", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
solarti-token = { version = "4.0", path = "../../token/program", features = ["no-entrypoint"] }
solarti-token-2022 = { version = "0.9", path = "../../token/program-2022", features = ["no-entrypoint"] }
solarti-token-client = { version = "0.4", path = "../../token/client" }
solarti-token-upgrade = { version = "0.1", path = "../program", features = ["no-entrypoint"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
miraland-test-validator = "1.14.18"

[[bin]]
name = "solarti-token-upgrade"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
