[package]
name = "solarti-token-upgrade-cli"
version = "0.1.1"
description = "SOLARTI Token Upgrade Command-line Utility"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = { version = "3", features = ["cargo"] }
futures-util = "0.3.19"
solana-clap-v3-utils = "1.14.12"
solana-cli-config = "1.14.12"
solana-client = "1.14.12"
solana-logger = "1.14.12"
solana-remote-wallet = "1.14.12"
solana-sdk = "1.14.12"
solarti-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
solarti-token = { version = "3.5", path = "../../token/program", features = ["no-entrypoint"] }
solarti-token-2022 = { version = "0.6", path = "../../token/program-2022", features = ["no-entrypoint"] }
solarti-token-client = { version = "0.4", path = "../../token/client" }
solarti-token-upgrade = { version = "0.1", path = "../program", features = ["no-entrypoint"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
solana-test-validator = "1.14.12"

[[bin]]
name = "solarti-token-upgrade"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
