[package]
name = "solarti-flash-loan-receiver"
version = "1.0.0"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
miraland-program = "=1.14.17-rc4"
solarti-token = { version = "3.5", path = "../../token/program", features=["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_flash_loan_receiver"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
