[package]
name = "solarti-flash-loan-receiver"
version = "1.0.0"
edition = "2021"

[dependencies]
arrayref = "0.3.7"
miraland-program = ">=1.18.5, <1.19.0"
solarti-token = { version = "4.0", path = "../../token/program", features = [
    "no-entrypoint",
] }

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_flash_loan_receiver"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
