[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
description = "solarti-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.miraland.top/token"
license = "Apache-2.0"
name = "solarti-transfer-hook-cli"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "0.0.1"

[dependencies]
clap = { version = "3", features = ["cargo"] }
futures-util = "0.3.19"
miraland-clap-v3-utils = "1.14.18"
miraland-cli-config = "1.14.18"
miraland-client = "1.18.2"
miraland-logger = "1.14.18"
miraland-remote-wallet = "1.14.18"
miraland-sdk = "1.14.18"
solarti-transfer-hook-interface = { version = "0.3", path = "../interface" }
solarti-tlv-account-resolution = { version = "0.4" , path = "../../../libraries/tlv-account-resolution" }
strum = "0.25"
strum_macros = "0.25"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
miraland-test-validator = "1.14.18"
solarti-token-2022 = { version = "0.9", path = "../../program-2022", features = ["no-entrypoint"] }
solarti-token-client = { version = "0.4", path = "../../client" }

[[bin]]
name = "solarti-transfer-hook"
path = "src/main.rs"
