[package]
name = "solarti-type-length-value-derive"
version = "0.3.9"
description = "Derive Macro Library for SPL Type Length Value traits"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true
name = "spl_type_length_value_derive"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
