[package]
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
description = "solarti-token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "solarti-token-client"
repository = "https://github.com/miraland-labs/solarti-program-library"
version = "0.4.3"

[dependencies]
async-trait = "0.1"
miraland-cli-output = {version = "=1.14.17", optional = true }
miraland-client = {version = "=1.14.17"}
miraland-program-test = {version = "=1.14.17"}
miraland-sdk = "=1.14.17"
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
solarti-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
solarti-memo = { version = "3.0", path = "../../memo/program", features = ["no-entrypoint"] }
solarti-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
solarti-token-2022 = { version = "0.6", path="../program-2022" }
thiserror = "1.0"

[features]
default = ["display"]
display = ["dep:miraland-cli-output"]
proof-program = []

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_client"