[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "solarti-token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "solarti-token-client"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.4.1"

[dependencies]
async-trait = "0.1"
miraland-cli-output = {path = "../../../miraland-1.14.17/cli-output", version = "=1.14.17-rc3", optional = true }
miraland-client = {path = "../../../miraland-1.14.17/client", version = "=1.14.17-rc3"}
miraland-program-test = {path = "../../../miraland-1.14.17/program-test", version = "1.14.17-rc3"}
miraland-sdk = {path = "../../../miraland-1.14.17/sdk", version = "1.14.17-rc3"}
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
solarti-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
solarti-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
solarti-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
solarti-token-2022 = { version = "0.6", path="../program-2022" }
thiserror = "1.0"

[features]
default = ["display"]
display = ["dep:miraland-cli-output"]
proof-program = []
