[package]
name = "solarti-transfer-hook-interface"
version = "0.3.0"
description = "Solarti Program Library Transfer Hook Interface"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.7"
bytemuck = { version = "1.14.0", features = ["derive"] }
miraland-program = "1.14.18"
solarti-discriminator = { version = "0.1" , path = "../../../libraries/discriminator" }
solarti-program-error = { version = "0.3" , path = "../../../libraries/program-error" }
solarti-tlv-account-resolution = { version = "0.4" , path = "../../../libraries/tlv-account-resolution" }
solarti-type-length-value = { version = "0.3" , path = "../../../libraries/type-length-value" }
solarti-pod = { version = "0.1", path = "../../../libraries/pod" }

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_transfer_hook_interface"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
