[package]
name = "solarti-binary-oracle-pair"
version = "0.1.0"
description = "Solarti Program Library Binary Oracle Pair"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.14.12"
solarti-token = { version = "3.5", path = "../../token/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
uint = "0.9"
borsh = "0.9.1"

[dev-dependencies]
solana-program-test = "1.14.12"
solana-sdk = "1.14.12"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_binary_oracle_pair"
