[package]
name = "solarti-example-custom-heap"
version = "1.0.0"
description = "Solarti Program Library Custom Heap Example"
authors = [
  "Miraland Crafters <crafters@miraland.top>",
  "Solana Labs Maintainers <maintainers@solanalabs.com>"
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
default = ["custom-heap"]
custom-heap = []
no-entrypoint = []
test-sbf = []

[dependencies]
miraland-program = ">=1.18.2"

[dev-dependencies]
miraland-program-test = ">=1.18.2"
miraland-sdk = ">=1.18.2"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_example_custom_heap"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
