[package]
name = "solarti-program-error-derive"
version = "0.3.11"
description = "Proc-Macro Library for Solarti Program error attributes and derive macro"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true
name = "spl_program_error_derive"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
sha2 = "0.10"
syn = { version = "2.0", features = ["full"] }
