[package]
name = "solarti-token-metadata-interface"
version = "0.2.8"
description = "Solarti Program Library Token Metadata Interface"
authors = [
  "Miraland Crafters <crafters@miraland.io>",
  "Miraland Labs Maintainers <maintainers@miralandlabs.com>",
]
repository = "https://github.com/miraland-labs/solarti-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
serde-traits = ["dep:serde", "solarti-pod/serde-traits"]

[dependencies]
borsh = "1.3.0"
serde = { version = "1.0.193", optional = true }
miraland-program = ">1.19.0"
solarti-discriminator = { version = "0.1.10", path = "../../libraries/discriminator" }
solarti-program-error = { version = "0.3.11", path = "../../libraries/program-error" }
solarti-type-length-value = { version = "0.3.9", path = "../../libraries/type-length-value" }
solarti-pod = { version = "0.1.10", path = "../../libraries/pod", features = [
  "borsh",
] }

[dev-dependencies]
serde_json = "1.0.108"

[lib]
crate-type = ["cdylib", "lib"]
name = "spl_token_metadata_interface"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
